//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""General"",
            ""id"": ""713f82ce-27c8-4349-96f5-6422198cfcf3"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""bf3b28c4-0074-4d32-a732-dbf0a6e1ad47"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Attack"",
                    ""type"": ""Button"",
                    ""id"": ""139170b0-adab-4dc0-9a4b-b7d9d54c1d93"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Menu"",
                    ""type"": ""Button"",
                    ""id"": ""dc2ebb37-e1bd-4222-81fa-2883f5fb5fda"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""WeaponAbility"",
                    ""type"": ""Button"",
                    ""id"": ""fbd1c8cc-c286-4263-9f57-747f550b4c50"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Ultimate"",
                    ""type"": ""Button"",
                    ""id"": ""7bbf3bfa-146c-4d1b-98a3-7b18c94c6250"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MovementAbility"",
                    ""type"": ""Button"",
                    ""id"": ""193ae4b0-df10-4189-b814-9ea28d1e2b24"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pickup"",
                    ""type"": ""Button"",
                    ""id"": ""712a576c-df50-43d4-add8-21eb355c76a7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Reload"",
                    ""type"": ""Button"",
                    ""id"": ""95d31c53-e25f-47c4-a2a6-96c3b16bf781"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""526248b9-d2fd-4bf7-8b38-df670739467e"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""bde778dc-8464-456f-bd8b-271bfd5cc08c"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""da887beb-23cd-469a-86b1-7dbe4687923c"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""6cd1cd7c-589c-405f-b0ef-f126ab6a036d"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""fa0ac801-ac98-40b4-a252-b2c9d95cfd9b"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""4fb18be3-20f3-4c52-ade6-fceaf40ae5b4"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""09c0398d-f646-4b6c-ad98-4dd46dbb63fe"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d3be0929-d3dd-45b2-96f0-cc97c4c18609"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WeaponAbility"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""93457902-2833-4109-8456-336a49b8afd5"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Ultimate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""28e1973f-a87a-4d58-aa44-6be0dfa2c38e"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementAbility"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""67740dc8-7dd9-435e-ac98-ce7bbb99976e"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pickup"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ec2dd1f0-72a1-4706-b625-80e99678d8b9"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Reload"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // General
        m_General = asset.FindActionMap("General", throwIfNotFound: true);
        m_General_Move = m_General.FindAction("Move", throwIfNotFound: true);
        m_General_Attack = m_General.FindAction("Attack", throwIfNotFound: true);
        m_General_Menu = m_General.FindAction("Menu", throwIfNotFound: true);
        m_General_WeaponAbility = m_General.FindAction("WeaponAbility", throwIfNotFound: true);
        m_General_Ultimate = m_General.FindAction("Ultimate", throwIfNotFound: true);
        m_General_MovementAbility = m_General.FindAction("MovementAbility", throwIfNotFound: true);
        m_General_Pickup = m_General.FindAction("Pickup", throwIfNotFound: true);
        m_General_Reload = m_General.FindAction("Reload", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // General
    private readonly InputActionMap m_General;
    private IGeneralActions m_GeneralActionsCallbackInterface;
    private readonly InputAction m_General_Move;
    private readonly InputAction m_General_Attack;
    private readonly InputAction m_General_Menu;
    private readonly InputAction m_General_WeaponAbility;
    private readonly InputAction m_General_Ultimate;
    private readonly InputAction m_General_MovementAbility;
    private readonly InputAction m_General_Pickup;
    private readonly InputAction m_General_Reload;
    public struct GeneralActions
    {
        private @PlayerControls m_Wrapper;
        public GeneralActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_General_Move;
        public InputAction @Attack => m_Wrapper.m_General_Attack;
        public InputAction @Menu => m_Wrapper.m_General_Menu;
        public InputAction @WeaponAbility => m_Wrapper.m_General_WeaponAbility;
        public InputAction @Ultimate => m_Wrapper.m_General_Ultimate;
        public InputAction @MovementAbility => m_Wrapper.m_General_MovementAbility;
        public InputAction @Pickup => m_Wrapper.m_General_Pickup;
        public InputAction @Reload => m_Wrapper.m_General_Reload;
        public InputActionMap Get() { return m_Wrapper.m_General; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GeneralActions set) { return set.Get(); }
        public void SetCallbacks(IGeneralActions instance)
        {
            if (m_Wrapper.m_GeneralActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_GeneralActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_GeneralActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_GeneralActionsCallbackInterface.OnMove;
                @Attack.started -= m_Wrapper.m_GeneralActionsCallbackInterface.OnAttack;
                @Attack.performed -= m_Wrapper.m_GeneralActionsCallbackInterface.OnAttack;
                @Attack.canceled -= m_Wrapper.m_GeneralActionsCallbackInterface.OnAttack;
                @Menu.started -= m_Wrapper.m_GeneralActionsCallbackInterface.OnMenu;
                @Menu.performed -= m_Wrapper.m_GeneralActionsCallbackInterface.OnMenu;
                @Menu.canceled -= m_Wrapper.m_GeneralActionsCallbackInterface.OnMenu;
                @WeaponAbility.started -= m_Wrapper.m_GeneralActionsCallbackInterface.OnWeaponAbility;
                @WeaponAbility.performed -= m_Wrapper.m_GeneralActionsCallbackInterface.OnWeaponAbility;
                @WeaponAbility.canceled -= m_Wrapper.m_GeneralActionsCallbackInterface.OnWeaponAbility;
                @Ultimate.started -= m_Wrapper.m_GeneralActionsCallbackInterface.OnUltimate;
                @Ultimate.performed -= m_Wrapper.m_GeneralActionsCallbackInterface.OnUltimate;
                @Ultimate.canceled -= m_Wrapper.m_GeneralActionsCallbackInterface.OnUltimate;
                @MovementAbility.started -= m_Wrapper.m_GeneralActionsCallbackInterface.OnMovementAbility;
                @MovementAbility.performed -= m_Wrapper.m_GeneralActionsCallbackInterface.OnMovementAbility;
                @MovementAbility.canceled -= m_Wrapper.m_GeneralActionsCallbackInterface.OnMovementAbility;
                @Pickup.started -= m_Wrapper.m_GeneralActionsCallbackInterface.OnPickup;
                @Pickup.performed -= m_Wrapper.m_GeneralActionsCallbackInterface.OnPickup;
                @Pickup.canceled -= m_Wrapper.m_GeneralActionsCallbackInterface.OnPickup;
                @Reload.started -= m_Wrapper.m_GeneralActionsCallbackInterface.OnReload;
                @Reload.performed -= m_Wrapper.m_GeneralActionsCallbackInterface.OnReload;
                @Reload.canceled -= m_Wrapper.m_GeneralActionsCallbackInterface.OnReload;
            }
            m_Wrapper.m_GeneralActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Attack.started += instance.OnAttack;
                @Attack.performed += instance.OnAttack;
                @Attack.canceled += instance.OnAttack;
                @Menu.started += instance.OnMenu;
                @Menu.performed += instance.OnMenu;
                @Menu.canceled += instance.OnMenu;
                @WeaponAbility.started += instance.OnWeaponAbility;
                @WeaponAbility.performed += instance.OnWeaponAbility;
                @WeaponAbility.canceled += instance.OnWeaponAbility;
                @Ultimate.started += instance.OnUltimate;
                @Ultimate.performed += instance.OnUltimate;
                @Ultimate.canceled += instance.OnUltimate;
                @MovementAbility.started += instance.OnMovementAbility;
                @MovementAbility.performed += instance.OnMovementAbility;
                @MovementAbility.canceled += instance.OnMovementAbility;
                @Pickup.started += instance.OnPickup;
                @Pickup.performed += instance.OnPickup;
                @Pickup.canceled += instance.OnPickup;
                @Reload.started += instance.OnReload;
                @Reload.performed += instance.OnReload;
                @Reload.canceled += instance.OnReload;
            }
        }
    }
    public GeneralActions @General => new GeneralActions(this);
    public interface IGeneralActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnAttack(InputAction.CallbackContext context);
        void OnMenu(InputAction.CallbackContext context);
        void OnWeaponAbility(InputAction.CallbackContext context);
        void OnUltimate(InputAction.CallbackContext context);
        void OnMovementAbility(InputAction.CallbackContext context);
        void OnPickup(InputAction.CallbackContext context);
        void OnReload(InputAction.CallbackContext context);
    }
}
